version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: restaurant-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  discovery-server:
    build: ./restaurant-discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"

  api-gateway:
    build: ./restaurant-gateway-service
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka

  identity-service:
    build: ./restaurant-identity-service
    container_name: identity-service
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/identity_db
      SPRING_DATASOURCE_USERNAME: identity_user
      SPRING_DATASOURCE_PASSWORD: identity_pass

  branch-service:
    build: ./restaurant-branch-service
    container_name: branch-service
    ports:
      - "8082:8080"
    depends_on:
      - postgres
      - discovery-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/branch_db
      SPRING_DATASOURCE_USERNAME: branch_user
      SPRING_DATASOURCE_PASSWORD: branch_pass
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/

  order-service:
    build: ./restaurant-order-service
    container_name: order-service
    ports:
      - "8083:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/order_db
      SPRING_DATASOURCE_USERNAME: order_user
      SPRING_DATASOURCE_PASSWORD: order_pass

  menu-service:
    build: ./restaurant-menu-service
    container_name: menu-service
    ports:
      - "8084:8080"
    depends_on:
      - postgres
      - discovery-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/menu_db
      SPRING_DATASOURCE_USERNAME: menu_user
      SPRING_DATASOURCE_PASSWORD: menu_pass
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/

  user-service:
    build: ./restaurant-user-service
    container_name: user
    ports:
      - "8084:8080"
    depends_on:
      - postgres
      - discovery-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_db
      SPRING_DATASOURCE_USERNAME: user_user
      SPRING_DATASOURCE_PASSWORD: user_pass
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/

volumes:
  postgres_data:
